name = "Twuble Modpack"
author = "ssamjh, Kikaiji"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91e5471d8b1e6a50fa6e09f73b8e92cde279e48b52ca9c6d1fa3b5c3f4b42df5"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
