name = "Twuble Modpack"
author = "ssamjh, Kikaiji"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50b342062f7602f8d9e20dceabe1f0fcefaf5c79bc30977536db284fbf89244f"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
