name = "Twuble Modpack"
author = "ssamjh, Kikaiji"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "815a51214a3bb1a2e177e2dcb788ea09152958ef020aea6292e573bf886dd3d6"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
