name = "Twuble Modpack"
author = "ssamjh, Kikaiji"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "825c20309c9ae9b976162c62dc59f428cce2d4ebfcca98dc9129fadeb809adef"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
