name = "Twuble Modpack"
author = "ssamjh, Kikaiji"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74d3943216694edfc8a7bf79c8727abb640efbcc72d9da9a09d4749ebadbb7d6"

[versions]
fabric = "0.15.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
